#ifndef DEVICE_MAP_H
#define DEVICE_MAP_H

// SDRAM
#define SDRAM_BASE_ADDR       0x00000000
#define SDRAM_SIZE            0x04000000  // 64 MB

// LEDs
#define LED_BASE_ADDR         0x04000000

// Toggle Switches
#define SWITCH_BASE_ADDR      0x04000010

// Timer (32-bit)
#define TIMER_BASE_ADDR       0x04000020
#define TIMER_STATUS_OFFSET   0x0
#define TIMER_CONTROL_OFFSET  0x1
#define TIMER_PERIODL_OFFSET  0x2
#define TIMER_PERIODH_OFFSET  0x3
#define TIMER_SNAPL_OFFSET    0x4
#define TIMER_SNAPH_OFFSET    0x5

#define TIMER_STATUS_ADDR     (TIMER_BASE_ADDR + TIMER_STATUS_OFFSET * 4)
#define TIMER_CONTROL_ADDR    (TIMER_BASE_ADDR + TIMER_CONTROL_OFFSET * 4)
#define TIMER_PERIODL_ADDR    (TIMER_BASE_ADDR + TIMER_PERIODL_OFFSET * 4)
#define TIMER_PERIODH_ADDR    (TIMER_BASE_ADDR + TIMER_PERIODH_OFFSET * 4)
#define TIMER_SNAPL_ADDR      (TIMER_BASE_ADDR + TIMER_SNAPL_OFFSET * 4)
#define TIMER_SNAPH_ADDR      (TIMER_BASE_ADDR + TIMER_SNAPH_OFFSET * 4)

// JTAG UART
#define JTAG_UART_BASE_ADDR   0x04000040

// Button
#define BUTTON_BASE_ADDR      0x040000D0

// VGA Pixel Buffer DMA
#define VGA_DMA_BASE_ADDR         0x04000100
#define VGA_DMA_BUFFER_OFFSET     0x0
#define VGA_DMA_BACKBUFFER_OFFSET 0x4
#define VGA_DMA_RESOLUTION_OFFSET 0x8
#define VGA_DMA_STATUS_OFFSET     0xC

#define VGA_DMA_BUFFER_ADDR       (VGA_DMA_BASE_ADDR + VGA_DMA_BUFFER_OFFSET)
#define VGA_DMA_BACKBUFFER_ADDR   (VGA_DMA_BASE_ADDR + VGA_DMA_BACKBUFFER_OFFSET)
#define VGA_DMA_RESOLUTION_ADDR   (VGA_DMA_BASE_ADDR + VGA_DMA_RESOLUTION_OFFSET)
#define VGA_DMA_STATUS_ADDR       (VGA_DMA_BASE_ADDR + VGA_DMA_STATUS_OFFSET)

// VGA Screen Buffer
#define VGA_SCREEN_BUFFER_ADDR    0x08000000

#endif // DEVICE_MAP_H
